apiVersion: v1
kind: PersistentVolume
metadata:
  name: default-pv
  labels:
    type: local
spec:
  storageClassName: default
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/pv/default"
